// Opening names for the Coach (src/coach/openings.*, src/coach/repertoire.*): the lichess book keyed by position
// hash, classification of a game record, the announcer's policy, the teaching repertoire, and the opening texts of
// the 10 languages (assets/coach/openings/<code>.lang, generated by tools/gen_opening_lang.py).
#include "test.h"
#include "coach/openings.h"
#include "coach/repertoire.h"
#include "core/embedded.h"
#include "i18n/i18n.h"

#include <algorithm>
#include <map>
#include <regex>
#include <set>
#include <sstream>

using namespace coach;

namespace {

const OpeningBook& book() { return OpeningBook::instance(); }

// Plays space-separated SAN moves from the start position.
chess::Game playLine(const std::string& sans) {
    chess::Game g;
    std::istringstream in(sans);
    std::string t;
    while (in >> t) {
        const chess::Move m = g.position().parseSAN(t);
        if (!m.valid()) std::fprintf(stderr, "  bad move %s in \"%s\"\n", t.c_str(), sans.c_str());
        CHECK(m.valid());
        if (!m.valid()) break;
        CHECK(g.play(m));
    }
    return g;
}

// The same game without its last 'n' plies (a takeback, rebuilt from the move list like the Coach can).
chess::Game takeBack(const chess::Game& g, int n) {
    chess::Game out;
    const std::vector<chess::Move>& moves = g.moves();
    for (size_t i = 0; i + size_t(n) < moves.size(); ++i) out.play(moves[i]);
    return out;
}

void playMore(chess::Game& g, const std::string& sans) {
    std::istringstream in(sans);
    std::string t;
    while (in >> t) {
        const chess::Move m = g.position().parseSAN(t);
        CHECK(m.valid());
        if (!m.valid()) return;
        g.play(m);
    }
}

uint64_t hashAfter(const std::string& sans) { return playLine(sans).position().hash(); }

std::string nameAt(uint64_t hash) {
    OpeningBook::Hit h;
    if (!book().lookup(hash, &h) || h.name < 0) return "";
    return book().name(h.name);
}

std::string famId(int f) { return f >= 0 ? book().families()[f].id : "-"; }
std::string varId(int v) { return v >= 0 ? book().variations()[v].id : "-"; }

std::vector<const OpeningEvent*> eventsOf(const OpeningState& st, OpeningEvent::Kind k) {
    std::vector<const OpeningEvent*> out;
    for (const OpeningEvent& e : st.events)
        if (e.kind == k) out.push_back(&e);
    return out;
}

std::string describe(const std::vector<OpeningLine>& lines) {
    std::string s;
    for (const OpeningLine& l : lines) {
        s += l.key + "(";
        for (const auto& a : l.args) s += a.first + "=" + (a.second.kind == OpeningArg::Kind::Number ? std::to_string(a.second.number) : a.second.text) + " ";
        s += ") ";
    }
    return s;
}

bool hasKey(const std::vector<OpeningLine>& lines, const std::string& key) {
    for (const OpeningLine& l : lines)
        if (l.key == key) return true;
    return false;
}

const std::vector<std::string>& langs() {
    static const std::vector<std::string> v = {"en", "fr", "de", "es", "ru", "uk", "ar", "ja", "zh-Hans", "zh-Hant"};
    return v;
}

std::map<std::string, std::string> loadLang(const std::string& code) {
    std::map<std::string, std::string> out;
    const std::string path = "assets/coach/openings/" + code + ".lang";
    CHECK(embedded::find(path.c_str()) != nullptr);
    std::vector<std::pair<std::string, std::string>> kv;
    std::string err;
    const bool ok = i18n::parse(embedded::text(path.c_str()), kv, &err);
    if (!ok) std::fprintf(stderr, "  %s: %s\n", path.c_str(), err.c_str());
    CHECK(ok);
    for (auto& p : kv) {
        if (out.count(p.first)) std::fprintf(stderr, "  %s: duplicate key %s\n", path.c_str(), p.first.c_str());
        CHECK(!out.count(p.first));
        out[p.first] = p.second;
    }
    return out;
}

// Placeholders of a value: {name} or {name:form}. names = true keeps the names only (a language may use another
// grammatical form of the same argument than English: "вариант {X:gen}" for "{X} Variation").
std::set<std::string> placeholders(const std::string& v, bool names = true) {
    std::set<std::string> out;
    for (size_t i = 0; i < v.size(); ++i) {
        if (v[i] != '{') continue;
        const size_t j = v.find('}', i);
        if (j == std::string::npos) break;
        std::string p = v.substr(i + 1, j - i - 1);
        if (names) p = p.substr(0, p.find(':'));
        out.insert(p);
        i = j;
    }
    return out;
}

bool endsWith(const std::string& s, const std::string& e) {
    return s.size() >= e.size() && s.compare(s.size() - e.size(), e.size(), e) == 0;
}

}  // namespace

// ---- The book ------------------------------------------------------------------------------------------------------
TEST(openings_book_counts) {
    const OpeningBook& b = book();
    CHECK(!b.empty());
    CHECK_EQ(b.rows(), size_t(3815));
    CHECK_EQ(b.namedPositions(), size_t(3815));   // each lichess line ends on its own position
    CHECK_EQ(b.duplicateNamedPositions(), size_t(0));
    CHECK_EQ(b.names(), size_t(3174));
    CHECK_EQ(b.positions(), size_t(7863));
    CHECK_EQ(b.leaves(), size_t(2379));
    CHECK_EQ(b.badTokens(), size_t(0));
    CHECK_EQ(b.families().size(), size_t(78));
    CHECK_EQ(b.variations().size(), size_t(66));
    std::fprintf(stderr, "  opening book built in %.1f ms\n", b.buildMs());
    CHECK(b.buildMs() < 2000.0);
}

TEST(openings_every_tsv_line_parses_and_names_its_position) {
    const OpeningBook& b = book();
    size_t rows = 0;
    for (const char* f : {"a", "b", "c", "d", "e"}) {
        const std::string text = embedded::text((std::string("assets/coach/openings_data/") + f + ".tsv").c_str());
        std::istringstream in(text);
        std::string line;
        while (std::getline(in, line)) {
            if (line.empty() || line.rfind("eco\t", 0) == 0) continue;
            ++rows;
            const size_t t1 = line.find('\t'), t2 = line.find('\t', t1 + 1);
            CHECK(t1 != std::string::npos && t2 != std::string::npos);
            if (t2 == std::string::npos) continue;
            const std::string name = line.substr(t1 + 1, t2 - t1 - 1);
            std::istringstream moves(line.substr(t2 + 1));
            chess::Position p;
            std::string tok;
            bool ok = true;
            while (moves >> tok) {
                if (tok.back() == '.') continue;   // move number
                const chess::Move m = p.parseSAN(tok);
                if (!m.valid()) ok = false;
                if (!ok) break;
                p.makeMove(m);
                CHECK(b.lookup(p.hash()));      // every prefix is a book position
            }
            CHECK(ok);
            if (nameAt(p.hash()) != name) {
                std::fprintf(stderr, "  %s: named \"%s\"\n", line.c_str(), nameAt(p.hash()).c_str());
                CHECK(false);
            }
        }
    }
    CHECK_EQ(rows, size_t(3815));
    CHECK(!b.lookup(chess::Position().hash()));   // the start position itself is not a book entry
    CHECK(!b.lookup(hashAfter("e4 a5 d4 h5")));   // out of book
}

TEST(openings_hash_identity_and_transpositions) {
    // The Queen's Gambit Declined reached from the English, from 1.d4 Nf6 and from the Queen's Gambit.
    const uint64_t qgd = hashAfter("d4 d5 c4 e6 Nc3 Nf6");
    CHECK_EQ(hashAfter("c4 e6 Nc3 d5 d4 Nf6"), qgd);
    CHECK_EQ(hashAfter("d4 Nf6 c4 e6 Nc3 d5"), qgd);
    CHECK_EQ(nameAt(qgd), std::string("Queen's Gambit Declined: Normal Defense"));
    CHECK_EQ(hashAfter("Nf3 d5 d4"), hashAfter("d4 d5 Nf3"));
    CHECK_EQ(nameAt(hashAfter("Nf3 d5 d4")), std::string("Queen's Pawn Game: Zukertort Variation"));
    // En passant counts only when capturable: 1.e4 equals the FEN position without an en passant square, as in
    // lichess's EPD convention.
    chess::Position fen;
    CHECK(fen.setFEN("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1"));
    CHECK_EQ(fen.hash(), hashAfter("e4"));
    CHECK_EQ(nameAt(fen.hash()), std::string("King's Pawn Game"));
}

TEST(openings_family_matching) {
    const OpeningBook& b = book();
    CHECK_EQ(famId(b.familyOf("Indian Defense: London System")), std::string("london"));
    CHECK_EQ(famId(b.familyOf("Queen's Gambit Declined")), std::string("qgd"));
    CHECK_EQ(famId(b.familyOf("Queen's Gambit Declined: Chigorin Defense, Main Line")), std::string("chigorin"));
    CHECK_EQ(famId(b.familyOf("Queen's Gambit")), std::string("queens_gambit"));
    CHECK_EQ(famId(b.familyOf("Vienna Gambit, with Max Lange Defense")), std::string("vienna"));
    CHECK_EQ(famId(b.familyOf("Queen's Gambit Accepted: Old Variation")), std::string("qga"));
    CHECK_EQ(b.familyOf("Amar Opening: Paris Gambit"), -1);   // a rare opening
    CHECK_EQ(OpeningBook::lichessFamily("Amar Opening: Paris Gambit"), std::string("Amar Opening"));
    CHECK_EQ(OpeningBook::lichessFamily("London System, with Be2"), std::string("London System"));
    CHECK_EQ(varId(b.variationOf("Sicilian Defense: Najdorf Variation, English Attack")), std::string("najdorf"));
    CHECK_EQ(b.variationOf("Sicilian Defense: Najdorfx"), -1);   // prefixes match at component boundaries only

    // Components beyond the notable variation, without the uninformative ones and move notation.
    int najdorfEnglish = -1, withMoves = -1;
    for (int n = 0; n < int(b.names()); ++n) {
        if (b.name(n) == "Sicilian Defense: Najdorf Variation, English Attack") najdorfEnglish = n;
        if (b.name(n) == "Queen's Indian Defense, with e3") withMoves = n;
    }
    CHECK(najdorfEnglish >= 0 && withMoves >= 0);
    CHECK(b.extraComponents(najdorfEnglish) == std::vector<std::string>{"English Attack"});
    CHECK(b.extraComponents(withMoves).empty());

    // Coverage: nearly every lichess line has a curated family, and every curated prefix still names a line
    // (run after replacing the TSVs with newer lichess data).
    size_t mapped = 0;
    std::set<std::string> used;
    for (int n = 0; n < int(b.names()); ++n) {
        if (b.familyOfName(n) >= 0) ++mapped;
        for (const OpeningFamily& f : b.families())
            for (const std::string& p : f.lichess)
                if (b.name(n) == p || b.name(n).rfind(p + ": ", 0) == 0 || b.name(n).rfind(p + ", ", 0) == 0)
                    used.insert(p);
        for (const OpeningVariation& v : b.variations())
            for (const std::string& p : v.lichess)
                if (b.name(n) == p || b.name(n).rfind(p + ": ", 0) == 0 || b.name(n).rfind(p + ", ", 0) == 0)
                    used.insert(p);
    }
    CHECK(mapped * 100 >= b.names() * 95);
    for (const OpeningFamily& f : b.families())
        for (const std::string& p : f.lichess)
            if (!used.count(p)) {
                std::fprintf(stderr, "  family %s: prefix \"%s\" names no line\n", f.id.c_str(), p.c_str());
                CHECK(false);
            }
    for (const OpeningVariation& v : b.variations())
        for (const std::string& p : v.lichess)
            if (!used.count(p)) {
                std::fprintf(stderr, "  variation %s: prefix \"%s\" names no line\n", v.id.c_str(), p.c_str());
                CHECK(false);
            }
    // Curated metadata: umbrellas, answers and generic placeholders.
    const OpeningFamily& qgd = b.families()[b.familyIndex("qgd")];
    CHECK_EQ(famId(qgd.umbrella), std::string("queens_gambit"));
    CHECK_EQ(qgd.answer, std::string("declined"));
    CHECK_EQ(b.families()[b.familyIndex("kga")].answer, std::string("accepted"));
    CHECK_EQ(famId(b.families()[b.familyIndex("kgd")].umbrella), std::string("kings_gambit"));
    CHECK(b.families()[b.familyIndex("kings_pawn")].generic);
    CHECK(b.families()[b.familyIndex("four_knights")].side == OpeningSide::Both);
}

// ---- Classification ------------------------------------------------------------------------------------------------
TEST(openings_classify_london_in_and_out_of_book) {
    const OpeningBook& b = book();
    // 3...e6 is a named leaf: the London is settled at once, then the game leaves the book.
    chess::Game g = playLine("d4 d5 Nf3 Nf6 Bf4 e6 e3 c5 c3 Nc6");
    OpeningState st = classify(g, b);
    CHECK(st.standardStart);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("london"));
    CHECK_EQ(st.side[chess::White].familyPly, 5);
    CHECK_EQ(famId(st.side[chess::White].generic), std::string("queens_pawn"));
    CHECK_EQ(st.side[chess::Black].family, -1);
    CHECK(st.determined);
    CHECK_EQ(st.determinedPly, 6);
    CHECK(st.determinedBy == DeterminedBy::NamedLeaf);
    CHECK_EQ(st.leftBookPly, 7);
    CHECK(!st.inBook);
    const auto fams = eventsOf(st, OpeningEvent::Kind::Family);
    CHECK_EQ(fams.size(), size_t(1));
    if (!fams.empty()) CHECK_EQ(famId(fams[0]->family), std::string("london"));
    // The London reached through 1...Nf6 ("Indian Defense: London System") is the same family.
    st = classify(playLine("d4 Nf6 Bf4"), b);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("london"));
    CHECK_EQ(st.side[chess::White].familyPly, 3);
    // Out of book, then back: a book position after the run of out-of-book plies is recognised again.
    g = playLine("d4 d5 Bf4 Nf6 e3 e6 Nf3 c5 c3 Nc6 Nbd2");
    st = classify(g, b);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("london"));
}

TEST(openings_classify_qgd_names_never_downgrade) {
    const OpeningBook& b = book();
    // 4.Bg5 is "QGD: Modern Variation", 4...Be7 only "Queen's Gambit Declined": White's label stays.
    chess::Game g = playLine("d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7");
    OpeningState st = classify(g, b);
    CHECK_EQ(b.name(st.lastNamed), std::string("Queen's Gambit Declined"));
    CHECK_EQ(st.side[chess::White].deep, std::string("Modern Variation"));
    CHECK_EQ(famId(st.side[chess::White].family), std::string("queens_gambit"));
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("qgd"));
    const auto fam = eventsOf(st, OpeningEvent::Kind::Family);
    const auto ans = eventsOf(st, OpeningEvent::Kind::Answer);
    CHECK_EQ(fam.size(), size_t(1));
    CHECK_EQ(ans.size(), size_t(1));
    if (!fam.empty()) CHECK_EQ(fam[0]->ply, 3);
    if (!ans.empty()) CHECK_EQ(ans[0]->ply, 4);
    // ... then the Orthodox Defense, Black's notable variation.
    playMore(g, "e3 O-O Nf3 Nbd7");
    st = classify(g, b);
    CHECK_EQ(varId(st.side[chess::Black].variation), std::string("qgd_orthodox"));
    CHECK_EQ(st.side[chess::Black].variationPly, 12);
    CHECK_EQ(st.side[chess::White].deep, std::string("Modern Variation"));
}

TEST(openings_classify_sicilian_najdorf) {
    const OpeningBook& b = book();
    chess::Game g = playLine("e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O");
    OpeningState st = classify(g, b);
    const auto fam = eventsOf(st, OpeningEvent::Kind::Family);
    CHECK_EQ(fam.size(), size_t(1));
    if (!fam.empty()) {
        CHECK_EQ(famId(fam[0]->family), std::string("sicilian"));
        CHECK_EQ(fam[0]->ply, 2);
        CHECK(fam[0]->owner == OpeningSide::Black);
    }
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("sicilian"));
    CHECK_EQ(varId(st.side[chess::Black].variation), std::string("najdorf"));
    CHECK_EQ(st.side[chess::Black].variationPly, 10);
    CHECK_EQ(varId(st.side[chess::White].variation), std::string("open_sicilian"));
    CHECK_EQ(famId(st.side[chess::White].generic), std::string("kings_pawn"));
    CHECK_EQ(st.side[chess::White].deep, std::string("English Attack"));   // 8.f3, credited to the mover
    CHECK(st.determined);
    CHECK_EQ(st.determinedPly, 15);
    CHECK(st.determinedBy == DeterminedBy::NamedLeaf);
    // A lower ply limit settles it earlier, while still in book.
    st = classify(g, b, 12);
    CHECK_EQ(st.determinedPly, 12);
    CHECK(st.determinedBy == DeterminedBy::PlyLimit);
}

TEST(openings_classify_kings_indian_waits_for_black) {
    const OpeningBook& b = book();
    // lichess names 3.Nc3 "King's Indian Defense", but Black has not chosen yet.
    OpeningState st = classify(playLine("d4 Nf6 c4 g6 Nc3"), b);
    CHECK_EQ(b.name(st.lastNamed), std::string("King's Indian Defense"));
    CHECK(eventsOf(st, OpeningEvent::Kind::Family).empty());
    CHECK_EQ(st.side[chess::Black].family, -1);
    st = classify(playLine("d4 Nf6 c4 g6 Nc3 Bg7"), b);
    const auto fam = eventsOf(st, OpeningEvent::Kind::Family);
    CHECK_EQ(fam.size(), size_t(1));
    if (!fam.empty()) {
        CHECK_EQ(famId(fam[0]->family), std::string("kings_indian"));
        CHECK_EQ(fam[0]->ply, 6);
    }
    // 3...d5 instead: the Grünfeld, and no King's Indian was ever credited.
    st = classify(playLine("d4 Nf6 c4 g6 Nc3 d5"), b);
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("grunfeld"));
    for (const OpeningEvent& e : st.events) CHECK(famId(e.family) != "kings_indian");
    // The Mar del Plata: the Classical (lichess "Orthodox") Variation is White's.
    st = classify(playLine("d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5"), b);
    CHECK_EQ(varId(st.side[chess::White].variation), std::string("kid_classical"));
}

TEST(openings_classify_grunfeld_exchange_is_whites) {
    const OpeningBook& b = book();
    // The lichess line ends on Black's forced recapture 4...Nxd5; the choice was White's 4.cxd5.
    OpeningState st = classify(playLine("d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5"), b);
    CHECK_EQ(varId(st.side[chess::White].variation), std::string("grunfeld_exchange"));
    CHECK_EQ(st.side[chess::Black].variation, -1);
    const auto v = eventsOf(st, OpeningEvent::Kind::Variation);
    CHECK_EQ(v.size(), size_t(1));
    if (!v.empty()) CHECK(v[0]->owner == OpeningSide::White);
}

TEST(openings_classify_umbrellas_and_transpositions) {
    const OpeningBook& b = book();
    // King's Gambit Accepted: White's opening is the King's Gambit, Black's answer accepts it.
    OpeningState st = classify(playLine("e4 e5 f4 exf4"), b);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("kings_gambit"));
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("kga"));
    CHECK_EQ(eventsOf(st, OpeningEvent::Kind::Answer).size(), size_t(1));
    // Queen's Gambit Accepted.
    st = classify(playLine("d4 d5 c4 dxc4"), b);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("queens_gambit"));
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("qga"));
    // The Slav answers the Queen's Gambit without accepting or declining it by name.
    st = classify(playLine("d4 d5 c4 c6"), b);
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("slav"));
    CHECK_EQ(famId(st.side[chess::White].family), std::string("queens_gambit"));
    // The English becomes a Queen's Gambit Declined; the out-of-book ply 4 does not settle anything.
    st = classify(playLine("c4 e6 Nc3 d5 d4 Nf6"), b);
    const auto fam = eventsOf(st, OpeningEvent::Kind::Family);
    const auto tr = eventsOf(st, OpeningEvent::Kind::Transposed);
    CHECK_EQ(fam.size(), size_t(1));
    CHECK_EQ(tr.size(), size_t(1));
    if (!fam.empty()) CHECK_EQ(famId(fam[0]->family), std::string("english"));
    if (!tr.empty()) {
        CHECK_EQ(famId(tr[0]->family), std::string("qgd"));
        CHECK_EQ(tr[0]->ply, 6);
    }
    CHECK_EQ(famId(st.side[chess::White].family), std::string("queens_gambit"));
    CHECK(!st.determined);
    CHECK(st.inBook);
    // The Four Knights belongs to both sides.
    st = classify(playLine("e4 e5 Nf3 Nc6 Nc3 Nf6"), b);
    CHECK_EQ(famId(st.side[chess::White].family), std::string("four_knights"));
    CHECK_EQ(famId(st.side[chess::Black].family), std::string("four_knights"));
    // A custom start position is never classified.
    chess::Game custom;
    CHECK(custom.resetFromFEN("4k3/8/8/8/8/8/4P3/4K3 w - - 0 1"));
    st = classify(custom, b);
    CHECK(!st.standardStart);
    CHECK(st.events.empty());
}

// ---- The announcer -------------------------------------------------------------------------------------------------
TEST(openings_announcer_policy_by_level) {
    const char* najdorf = "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O Qd2";
    for (int level = 0; level <= 6; ++level) {
        OpeningAnnouncer a;
        a.setLevel(level);
        a.setHumanColor(chess::White);
        chess::Game g;
        std::vector<std::pair<int, std::vector<OpeningLine>>> said;
        std::istringstream in(najdorf);
        std::string t;
        while (in >> t) {
            const chess::Move m = g.position().parseSAN(t);
            if (!m.valid()) break;
            g.play(m);
            std::vector<OpeningLine> lines = a.update(g);
            if (!lines.empty()) said.push_back({int(g.moves().size()), lines});
        }
        if (level == 0) {
            CHECK(said.empty());   // the rules lesson never names openings
            continue;
        }
        CHECK(!said.empty());
        if (said.empty()) continue;
        // The first utterance names both sides once the opening is settled, then comments on it.
        CHECK_EQ(said[0].first, std::min(openingPlyLimit(level), 15));
        const std::vector<OpeningLine>& first = said[0].second;
        CHECK(first[0].key.rfind("opening.say.pw.", 0) == 0);
        bool comment = false;
        for (const OpeningLine& l : first)
            if (endsWith(l.key, ".beginner") || endsWith(l.key, ".advanced")) {
                comment = true;
                CHECK_EQ(endsWith(l.key, ".advanced"), level >= 4);
            }
        CHECK(comment);
        // Levels 1-2 name families only (the Najdorf has no beginner comment); level 3+ adds the variation.
        CHECK_EQ(hasKey(first, "opening.say.variation"), level >= 3);
        CHECK_EQ(hasKey(first, "opening.say.pw.var_white"), level >= 3);   // the Open Sicilian
        CHECK_EQ(hasKey(first, "opening.say.deep"), level >= 6);            // "English Attack"
        // At most one opening utterance per full move.
        for (size_t i = 1; i < said.size(); ++i) CHECK(said[i].first - said[i - 1].first >= 2);
        if (level >= 5) {   // the move where theory ended
            bool leftBook = false;
            for (const auto& s : said) leftBook = leftBook || hasKey(s.second, "opening.say.left_book_move");
            CHECK(leftBook);
        }
        if (level >= 1) std::fprintf(stderr, "  level %d, ply %d: %s\n", level, said[0].first, describe(first).c_str());
    }
}

TEST(openings_announcer_sentences) {
    // Declined umbrella, human Black.
    OpeningAnnouncer a;
    a.setLevel(1);
    a.setHumanColor(chess::Black);
    chess::Game g = playLine("d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7");
    std::vector<OpeningLine> lines = a.update(g);
    CHECK(!lines.empty());
    if (!lines.empty()) {
        CHECK_EQ(lines[0].key, std::string("opening.say.pb.declined"));
        CHECK_EQ(lines[0].args.size(), size_t(1));
        CHECK_EQ(lines[0].args[0].second.text, std::string("family:queens_gambit"));
        CHECK_EQ(OpeningTexts::instance().render(lines[0], "en", false),
                 std::string("I played the Queen's Gambit, and you declined it."));
    }
    // The Four Knights: one name for both sides.
    OpeningAnnouncer b;
    b.setLevel(2);
    lines = b.update(playLine("e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bb4"));
    CHECK(!lines.empty());
    if (!lines.empty()) CHECK_EQ(lines[0].key, std::string("opening.say.both"));
    // Levels 1-2: the coach's own tier-3 family is not named (the human's is).
    OpeningAnnouncer c;
    c.setLevel(1);
    c.setHumanColor(chess::White);
    lines = c.update(playLine("g4 d5 Bg2 e5 c4"));
    CHECK(!lines.empty());
    if (!lines.empty()) {
        CHECK_EQ(lines[0].key, std::string("opening.say.pw.white"));
        CHECK_EQ(lines[0].args[0].second.text, std::string("family:grob"));
    }
    // End-of-game summary: whatever the opening became, without changing what was said.
    OpeningAnnouncer d;
    d.setLevel(4);
    d.setHumanColor(chess::White);
    lines = d.summary(playLine("e4 e6 d4 d5 e5 c5"));
    CHECK_EQ(lines.size(), size_t(1));
    if (!lines.empty()) {
        CHECK_EQ(lines[0].key, std::string("opening.say.pw.var_white"));
        CHECK_EQ(OpeningTexts::instance().render(lines[0], "en", false),
                 std::string("I answered with the French Defense, and you went for the Advance Variation."));
    }
    CHECK_EQ(d.utterances(), 0);
}

TEST(openings_announcer_deterministic_and_silent_after_takeback) {
    const std::string line = "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5";
    auto run = [&](OpeningAnnouncer& a, chess::Game& g, const std::string& sans) {
        std::string out;
        std::istringstream in(sans);
        std::string t;
        while (in >> t) {
            g.play(g.position().parseSAN(t));
            out += describe(a.update(g));
        }
        return out;
    };
    OpeningAnnouncer a1, a2;
    for (OpeningAnnouncer* a : {&a1, &a2}) {
        a->setLevel(3);
        a->setHumanColor(chess::White);
    }
    chess::Game g1, g2;
    const std::string s1 = run(a1, g1, line), s2 = run(a2, g2, line);
    CHECK_EQ(s1, s2);
    CHECK(!s1.empty());
    CHECK_EQ(a1.utterances(), 1);
    // Take back two plies and replay the same moves: nothing new to say.
    chess::Game back = takeBack(g1, 2);
    CHECK(a1.update(back).empty());
    CHECK_EQ(run(a1, back, "Be3 e5"), std::string());
    // Take back to 5.Nc3 and play the Dragon instead: only the new variation is announced.
    back = takeBack(g1, 3);
    CHECK(a1.update(back).empty());
    std::string after;
    for (const char* m : {"g6", "Be3", "Bg7"}) {
        back.play(back.position().parseSAN(m));
        const std::vector<OpeningLine> lines = a1.update(back);
        after += describe(lines);
        for (const OpeningLine& l : lines) CHECK(l.key.find("opening.say.pw.") != 0);   // not the summary again
    }
    CHECK(after.find("variation:dragon") != std::string::npos);
    CHECK(after.find("variation:najdorf") == std::string::npos);
    // A new game forgets the names but remembers which comments were said this session.
    a1.newGame();
    chess::Game g3;
    const std::string s3 = run(a1, g3, line);
    CHECK(s3.find("opening.say.pw.") != std::string::npos);
    CHECK(s3.find("opening.family.sicilian.beginner") == std::string::npos);
}

TEST(openings_announcer_sees_a_replaced_move_as_a_takeback) {
    // The human's move taken back and another played before the next update (an accepted takeback offer): the same
    // ply count, but the new opening is summed up again rather than worded as a transposition.
    OpeningAnnouncer a;
    a.setLevel(3);
    a.setHumanColor(chess::Black);
    chess::Game g;
    std::string said;
    for (const char* m : {"c4", "Nc6", "d4", "Nf6"}) {
        playMore(g, m);
        said += describe(a.update(g));
    }
    CHECK(said.find("opening.say.pb.") != std::string::npos);
    chess::Game back = takeBack(g, 1);
    playMore(back, "d5");
    const std::vector<OpeningLine> lines = a.update(back);
    CHECK(!lines.empty());
    if (!lines.empty()) CHECK(lines[0].key.rfind("opening.say.pb.", 0) == 0);
    CHECK(!hasKey(lines, "opening.say.transposed"));
    CHECK(describe(lines).find("family:chigorin") != std::string::npos);
}

TEST(openings_announcer_waits_for_speech_and_catches_up_silently) {
    OpeningAnnouncer a;
    a.setLevel(1);
    a.setHumanColor(chess::White);
    chess::Game g = playLine("e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6");
    CHECK(a.update(g, false).empty());   // speech busy: the talk waits
    CHECK(!a.update(g, true).empty());   // said when speech is free
    CHECK(a.update(g, true).empty());
    // Bulk moves (a resumed game): everything shown so far counts as said.
    OpeningAnnouncer b;
    b.setLevel(6);
    chess::Game h = playLine("e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O");
    b.catchUp(h);
    CHECK(b.update(h).empty());
    playMore(h, "O-O-O");
    CHECK(b.update(h).empty());
    CHECK_EQ(b.utterances(), 0);
    // Custom start positions and level 0 are silent.
    OpeningAnnouncer c;
    c.setLevel(3);
    chess::Game custom;
    CHECK(custom.resetFromFEN("r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3"));
    playMore(custom, "Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O");
    CHECK(c.update(custom).empty());
}

// ---- The teaching repertoire -----------------------------------------------------------------------------------------
TEST(openings_repertoire_table) {
    std::string err;
    const bool ok = checkRepertoireTable(book(), &err);
    if (!ok) std::fprintf(stderr, "  %s\n", err.c_str());
    CHECK(ok);
}

TEST(openings_repertoire_moves_are_legal_and_in_book) {
    const OpeningBook& b = book();
    int played = 0;
    for (int level = 1; level <= 6; ++level) {
        for (chess::Color coach : {chess::White, chess::Black}) {
            for (uint64_t seed = 1; seed <= 25; ++seed) {
                chess::Game g;
                uint64_t rng = seed * 7919 + uint64_t(level) * 31 + coach;
                auto next = [&rng]() {
                    rng = rng * 6364136223846793005ull + 1442695040888963407ull;
                    return uint32_t(rng >> 33);
                };
                for (int ply = 0; ply < 24 && !g.isOver(); ++ply) {
                    const chess::Position& pos = g.position();
                    chess::Move m;
                    if (pos.sideToMove() == coach) {
                        m = repertoireMove(g, level, seed);
                        CHECK(m == repertoireMove(g, level, seed));   // deterministic
                        if (m.valid()) {
                            ++played;
                            CHECK(pos.isLegal(m));
                            CHECK(ply < kRepertoireMaxPly);
                            chess::Position after = pos;
                            after.makeMove(m);
                            CHECK(b.lookup(after.hash()));
                            CHECK(ply == 0 || b.lookup(pos.hash()));
                        }
                    }
                    const std::vector<chess::Move> legal = pos.legalMoves();
                    if (!m.valid()) {
                        // The human, or Stockfish's stand-in: main lines half of the time (a player who knows
                        // theory), otherwise any book move, and sometimes anything.
                        const uint32_t r = next() % 10;
                        if (r >= 5 && pos.sideToMove() != coach) m = repertoireMove(g, 1 + int(next() % 6), next());
                        if (!m.valid()) {
                            std::vector<chess::Move> inBook;
                            for (const chess::Move& c : legal) {
                                chess::Position after = pos;
                                after.makeMove(c);
                                if (b.lookup(after.hash())) inBook.push_back(c);
                            }
                            const std::vector<chess::Move>& from = r == 0 || inBook.empty() ? legal : inBook;
                            m = from[next() % from.size()];
                        }
                    }
                    g.play(m);
                }
            }
        }
    }
    std::fprintf(stderr, "  %d repertoire moves played\n", played);
    CHECK(played > 500);
    // The curated first moves at levels 1-2: 1.e4 as White, 1...e5 against 1.e4, 1...d5 against 1.d4.
    for (uint64_t seed = 1; seed <= 20; ++seed) {
        chess::Game g;
        CHECK(g.position().toSAN(repertoireMove(g, 1, seed)) == "e4");
        CHECK(playLine("e4").position().toSAN(repertoireMove(playLine("e4"), 2, seed)) == "e5");
        CHECK(playLine("d4").position().toSAN(repertoireMove(playLine("d4"), 1, seed)) == "d5");
        const std::string third = playLine("e4 e5 Nf3 Nc6").position().toSAN(repertoireMove(playLine("e4 e5 Nf3 Nc6"), 1, seed));
        CHECK(third == "Bc4" || third == "d4");
    }
    // Different seeds give some variety at the higher levels.
    std::set<std::string> firsts;
    for (uint64_t seed = 1; seed <= 40; ++seed) firsts.insert(chess::Game().position().toSAN(repertoireMove(chess::Game(), 6, seed)));
    CHECK(firsts.size() >= 3);
    // Stockfish plays: level 0, custom start, out of book, from ply 16.
    CHECK(!repertoireMove(chess::Game(), 0, 1).valid());
    chess::Game custom;
    CHECK(custom.resetFromFEN("rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1"));
    CHECK(!repertoireMove(custom, 3, 1).valid());
    CHECK(!repertoireMove(playLine("e4 a5 d4 h5"), 3, 1).valid());
    CHECK(!repertoireMove(playLine("e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7"), 6, 1).valid());
}

// ---- Texts -----------------------------------------------------------------------------------------------------------
TEST(openings_lang_files_match_english) {
    const std::map<std::string, std::string> en = loadLang("en");
    CHECK(en.size() > 800);
    for (const std::string& code : langs()) {
        const std::map<std::string, std::string> got = code == "en" ? en : loadLang(code);
        for (const auto& kv : en) {
            auto it = got.find(kv.first);
            if (it == got.end()) {
                std::fprintf(stderr, "  %s: missing %s\n", code.c_str(), kv.first.c_str());
                CHECK(false);
                continue;
            }
            CHECK(!it->second.empty());
            if (placeholders(it->second) != placeholders(kv.second)) {
                std::fprintf(stderr, "  %s: placeholders of %s differ\n", code.c_str(), kv.first.c_str());
                CHECK(false);
            }
        }
        for (const auto& kv : got)
            if (!en.count(kv.first)) {
                std::fprintf(stderr, "  %s: extra key %s\n", code.c_str(), kv.first.c_str());
                CHECK(false);
            }
    }
}

TEST(openings_every_name_and_form_in_every_language) {
    const OpeningBook& b = book();
    const OpeningTexts& t = OpeningTexts::instance();
    for (const std::string& lang : langs()) {
        // Forms this language's sentences use ({white:def}...): every family and variation must define them.
        std::set<std::string> forms;
        for (const auto& kv : loadLang(lang))
            if (kv.first.rfind("opening.say.", 0) == 0)
                for (const std::string& p : placeholders(kv.second, false)) {
                    const size_t c = p.find(':');
                    if (c != std::string::npos && p.substr(c + 1) != "nom") forms.insert(p.substr(c + 1));
                }
        CHECK(lang != "en" || forms.count("def") == 1);
        for (const OpeningFamily& f : b.families()) {
            const std::string base = "opening.family." + f.id;
            CHECK(t.find(lang, base) && !t.find(lang, base)->empty());
            for (const std::string& form : forms) CHECK(t.find(lang, base + "." + form) != nullptr);
            CHECK(t.find(lang, base + ".beginner") && t.find(lang, base + ".advanced"));
            CHECK(!t.arg("family:" + f.id, "def", lang, true).empty());
        }
        for (const OpeningVariation& v : b.variations()) {
            const std::string base = "opening.variation." + v.id;
            CHECK(t.find(lang, base) && !t.find(lang, base)->empty());
            for (const std::string& form : forms) CHECK(t.find(lang, base + "." + form) != nullptr);
            CHECK(t.find(lang, base + ".advanced") != nullptr);
            CHECK_EQ(t.find(lang, base + ".beginner") != nullptr, v.beginnerComment);
            CHECK(!t.arg("variation:" + v.id, "", lang, false).empty());
        }
    }
}

TEST(openings_texts_render_and_speak) {
    const OpeningTexts& t = OpeningTexts::instance();
    OpeningLine l{"opening.say.pw.both", {{"white", {OpeningArg::Kind::Opening, "family:italian", 0}},
                                          {"black", {OpeningArg::Kind::Opening, "variation:two_knights", 0}}}};
    CHECK_EQ(t.render(l, "en", false, 0), std::string("You opened with the Italian Game, and I answered with the Two Knights Defense."));
    CHECK_EQ(t.variants("opening.say.pw.both"), 2);
    CHECK(t.render(l, "en", false, 1) != t.render(l, "en", false, 0));
    for (const std::string& lang : langs()) {
        const std::string written = t.render(l, lang, false, 0), spoken = t.render(l, lang, true, 0);
        CHECK(!written.empty() && !spoken.empty());
        CHECK(written.find('{') == std::string::npos);
    }
    std::fprintf(stderr, "  fr: %s\n  ru: %s\n  ja: %s\n", t.render(l, "fr", false, 0).c_str(),
                 t.render(l, "ru", false, 0).c_str(), t.render(l, "ja", false, 0).c_str());
    // English speech respells names for the voice; Russian and Ukrainian speech drop the dash inside names.
    CHECK_EQ(t.arg("variation:najdorf", "def", "en", true), std::string("the Nigh-dorf Variation"));
    CHECK_EQ(t.arg("variation:najdorf", "def", "en", false), std::string("the Najdorf Variation"));
    CHECK(t.arg("family:caro_kann", "", "ru", false).find("\xE2\x80\x94") != std::string::npos);
    CHECK(t.arg("family:caro_kann", "", "ru", true).find("\xE2\x80\x94") == std::string::npos);
    CHECK(t.arg("family:caro_kann", "", "uk", true).find("\xE2\x80\x94") == std::string::npos);
    CHECK_EQ(fixNameDashesForSpeech("Защита Каро — Канн"), std::string("Защита Каро-Канн"));
    CHECK_EQ(fixNameDashesForSpeech("Ваш дебют — защита"), std::string("Ваш дебют — защита"));
    // Squares are spelled out for the voice.
    const std::string* c = t.find("en", "opening.family.italian.beginner.spoken");
    CHECK(c && c->find("see four") != std::string::npos);
    // Composed lichess variation names.
    CHECK_EQ(t.arg("line:Paulsen Attack", "", "en", false), std::string("Paulsen Attack"));
    CHECK_EQ(t.arg("line:Paulsen Attack", "", "fr", false), std::string("attaque Paulsen"));
    CHECK_EQ(t.arg("line:Paulsen Attack", "", "de", false), std::string("Paulsen-Angriff"));
    CHECK_EQ(t.arg("line:Paulsen Attack", "", "es", false), std::string("ataque Paulsen"));
    CHECK(!t.arg("line:Paulsen Attack", "", "ru", false).empty());   // through the eponym table
    CHECK_EQ(t.arg("line:English Attack", "", "fr", false), std::string());   // a common word: not composed
    CHECK_EQ(t.arg("line:English Attack", "", "zh-Hans", false), std::string("English Attack"));
    CHECK_EQ(t.arg("line:Exchange Variation", "", "fr", false), *t.find("fr", "opening.component.exchange_variation"));
    // The rare, unnamed case renders everywhere.
    for (const std::string& lang : langs()) CHECK(!t.render(OpeningLine{"opening.say.rare", {}}, lang, true).empty());
}

TEST(openings_texts_speech_forms) {
    // Every ".spoken" key belongs to a written key; English speech has no squares left in it; comments name pieces
    // in words (no piece-letter notation, which the voice could not read).
    const std::regex square("(^|[^A-Za-z0-9])[a-h][1-8]($|[^A-Za-z0-9])");
    const std::regex san("(^|[^A-Za-z])[KQRBN][a-h]?[1-8]?x?[a-h][1-8]");
    for (const std::string& lang : langs()) {
        const std::map<std::string, std::string> m = loadLang(lang);
        for (const auto& kv : m) {
            if (endsWith(kv.first, ".spoken")) {
                const std::string base = kv.first.substr(0, kv.first.size() - 7);
                CHECK(m.count(base) == 1);
                if (lang != "zh-Hans" && lang != "zh-Hant" && std::regex_search(kv.second, square)) {
                    std::fprintf(stderr, "  %s: square left in %s\n", lang.c_str(), kv.first.c_str());
                    CHECK(false);
                }
            } else if ((endsWith(kv.first, ".beginner") || endsWith(kv.first, ".advanced")) &&
                       std::regex_search(kv.second, san)) {
                std::fprintf(stderr, "  %s: piece-letter notation in %s\n", lang.c_str(), kv.first.c_str());
                CHECK(false);
            }
        }
    }
}
