#include "embedded.h"
#include "log.h"
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>

// Generated by cmake/embed.cmake into the build directory.
extern const embedded::File g_embeddedFiles[];
extern const size_t g_embeddedFileCount;

namespace embedded {
static std::string g_overrideDir;

void setOverrideDir(const std::string& dir) { g_overrideDir = dir; }

const File* find(const char* path) {
    for (size_t i = 0; i < g_embeddedFileCount; ++i)
        if (std::strcmp(g_embeddedFiles[i].path, path) == 0) return &g_embeddedFiles[i];
    return nullptr;
}

std::string text(const char* path) {
    if (!g_overrideDir.empty()) {
        // A UTF-8 path: a wide one on Windows (u8path), whatever the process code page.
        std::ifstream f(std::filesystem::u8path(g_overrideDir + "/" + path), std::ios::binary);
        if (f) {
            std::stringstream ss;
            ss << f.rdbuf();
            return ss.str();
        }
    }
    const File* f = find(path);
    if (!f) {
        LOGE("embedded file not found: %s", path);
        return std::string();
    }
    return std::string(reinterpret_cast<const char*>(f->data), f->size);
}

const File* all(size_t* count) {
    *count = g_embeddedFileCount;
    return g_embeddedFiles;
}
}  // namespace embedded
