// Opening names for the Coach: which opening each side chose, when the choice is settled, what the coach says
// about it, and the coach's own teaching repertoire. Engine-free (no Stockfish, no GL), unit-tested in
// tests/openings_tests.cpp.
//
// Data (embedded assets):
//   assets/coach/openings_data/{a..e}.tsv   lichess chess-openings (CC0), verbatim: 3,815 named lines
//   assets/coach/openings_data/openings.json curated families (78) and notable variations (66): side, tier,
//                                            umbrella, lichess name prefixes (generated, no text)
//   assets/coach/openings/<code>.lang        names, comments and sentences in the 10 UI languages
// The .json and .lang files are generated by tools/gen_opening_lang.py from tools/openings_source/.
//
// Flow: OpeningBook (immutable table keyed by Position::hash) -> classify(game) (stateless: replays the game,
// so takebacks and transpositions need no special care) -> OpeningAnnouncer (remembers what was said, decides
// what to say for the coach's level) -> OpeningLine (a catalog key plus typed arguments, rendered by the speech
// catalog or by OpeningTexts below). The coach's own opening moves: coach/repertoire.h.
#pragma once
#include "chess/chess.h"
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>

namespace coach {

// Who chooses an opening. Families carry a curated side because move parity is wrong for some lichess names
// (the King's Indian is named at 3.Nc3, before Black chose it; the Grünfeld Exchange ends on Black's forced
// recapture). Both = the Four Knights Game.
enum class OpeningSide : uint8_t { White, Black, Both };

struct OpeningFamily {
    std::string id;                    // "sicilian" (catalog keys opening.family.<id>...)
    std::vector<std::string> lichess;  // lichess name prefixes that belong to it (longest prefix wins)
    OpeningSide side = OpeningSide::White;
    int tier = 3;                      // 1 very common ... 3 occasional (estimated frequency at club level)
    bool generic = false;              // placeholder (1.e4, 1.d4, 1.Nf3, 1.d4 Nf6, 2.Nf3): only a fallback name
    int umbrella = -1;                 // family White's opening becomes when Black answers with this one
                                       // (QGD -> Queen's Gambit, KGA -> King's Gambit), -1 = none
    std::string answer;                // "declined" / "accepted" for the umbrella answers that are, else ""
    std::string structure;             // open | semi-open | closed | indian | flank
    std::string character;             // quiet | balanced | sharp | gambit
};

struct OpeningVariation {
    std::string id;                    // "najdorf" (catalog keys opening.variation.<id>...)
    int family = -1;                   // index in OpeningBook::families()
    OpeningSide side = OpeningSide::White;
    std::vector<std::string> lichess;
    bool beginnerComment = false;      // has opening.variation.<id>.beginner (a line beginners meet)
};

// ---- The book ----------------------------------------------------------------------------------------------------
// Every position on every lichess line, keyed by Position::hash() (Zobrist: pieces, side to move, castling rights,
// en passant only when capturable, which is lichess's EPD identity; move counters are ignored, so transpositions
// with different move numbers match). Immutable once built; safe to read from any thread.
class OpeningBook {
public:
    // The book built from the embedded assets on first use (~40 ms; thread-safe). Empty if the assets are
    // missing or malformed (logged); every query then answers "out of book".
    static const OpeningBook& instance();

    // Builds from the text of the five TSV files and the metadata JSON (tests). False on malformed metadata.
    bool build(const std::vector<std::string>& tsvFiles, const std::string& metadataJson, std::string* error = nullptr);

    struct Hit {
        int name = -1;           // lichess name index, -1 = unnamed position inside a longer line
        bool hasDeeper = false;  // a longer line passes through it (else a named leaf)
    };
    bool lookup(uint64_t hash, Hit* out = nullptr) const;   // false = out of book
    bool empty() const { return entries_.empty(); }

    const std::string& name(int index) const;                // "Sicilian Defense: Najdorf Variation"
    int familyOfName(int nameIndex) const;                   // curated family, -1 = unmapped (a rare opening)
    int variationOfName(int nameIndex) const;                // notable variation, -1 = none
    // Longest lichess prefix at a component boundary ("", ": " or ", " follows it), -1 when none.
    int familyOf(const std::string& lichessName) const;
    int variationOf(const std::string& lichessName) const;
    // Components of a lichess name after the curated prefix that classified it, without the uninformative ones
    // ("Main Line", "Normal Variation"...), "with ..." and move notation: "Sicilian Defense: Najdorf Variation,
    // English Attack" -> {"English Attack"} (the Najdorf being the notable variation).
    std::vector<std::string> extraComponents(int nameIndex) const;
    // Lichess family part of a name ("Amar Opening: Paris Gambit" -> "Amar Opening").
    static std::string lichessFamily(const std::string& lichessName);

    const std::vector<OpeningFamily>& families() const { return families_; }
    const std::vector<OpeningVariation>& variations() const { return variations_; }
    int familyIndex(const std::string& id) const;
    int variationIndex(const std::string& id) const;

    // Lines through a position that suit the teaching repertoire: curated family of tier <= maxTier (1 or 2),
    // not a gambit, no trap or dubious sideline in the name. 0 when out of book, and 0 when the position itself
    // carries a name that is not a teaching line.
    int teachingLines(uint64_t hash, int maxTier) const;

    // Statistics (tests): rows read, named rows, distinct names, book positions, named leaves, SAN tokens that did
    // not parse, build time.
    size_t rows() const { return rows_; }
    size_t namedPositions() const { return named_; }
    size_t names() const { return names_.size(); }
    size_t positions() const { return entries_.size(); }
    size_t leaves() const { return leaves_; }
    size_t badTokens() const { return bad_; }
    size_t duplicateNamedPositions() const { return dupNamed_; }
    double buildMs() const { return buildMs_; }

private:
    struct Entry {
        uint64_t hash = 0;
        int32_t name = -1;
        uint16_t teach[2] = {0, 0};   // teaching lines, tier <= 1 and tier <= 2
        uint8_t flags = 0;            // 1 = has deeper lines
    };
    std::vector<Entry> entries_;      // sorted by hash
    std::vector<std::string> names_;
    std::vector<int> nameFamily_, nameVariation_, nameFamilyPrefix_, nameVariationPrefix_;  // prefix lengths
    std::vector<OpeningFamily> families_;
    std::vector<OpeningVariation> variations_;
    std::vector<std::string> ignored_;
    size_t rows_ = 0, named_ = 0, leaves_ = 0, bad_ = 0, dupNamed_ = 0;
    double buildMs_ = 0.0;
    const Entry* find(uint64_t hash) const;
    bool parseMetadata(const std::string& json, std::string* error);
    int longestPrefix(const std::string& name, bool variations, int* prefixLength) const;
};

// ---- Classification ----------------------------------------------------------------------------------------------
enum class DeterminedBy : uint8_t { None, NamedLeaf, OutOfBook, PlyLimit };

struct OpeningEvent {
    enum class Kind : uint8_t {
        Family,      // first specific family, chosen by its owner (who has just moved inside it)
        Answer,      // Black's family answers White's umbrella family (QGD after the Queen's Gambit)
        Transposed,  // another specific family after an earlier one
        Variation,   // a notable variation reached (curated side)
        Deep,        // new lichess components beyond the notable variation (credited to the side that moved)
        LeftBook,    // two consecutive plies out of book after being in book (ply = the first of the two)
        Determined   // the opening is settled (named leaf, two plies out of book, or the ply limit)
    };
    Kind kind = Kind::Family;
    int ply = 0;                         // plies played when it happened (1 = after White's first move)
    OpeningSide owner = OpeningSide::White;
    int family = -1, variation = -1;     // curated indices
    std::string deep;                    // Deep: the lichess component ("English Attack")
    DeterminedBy by = DeterminedBy::None;
};

// Names credited to one side. Never downgraded: a later, less specific position name keeps them; a change of
// family (transposition) replaces the variation and deep labels of the old family.
struct OpeningSideLabels {
    int family = -1, familyPly = -1;     // specific family chosen by this side (or the umbrella for White)
    int generic = -1, genericPly = -1;   // latest generic family of this side's moves (King's Pawn...)
    int variation = -1, variationPly = -1;
    std::string deep; int deepPly = -1;  // latest deep lichess component credited to this side
};

struct OpeningState {
    bool standardStart = true;           // false: custom start position, nothing is classified
    int plies = 0;
    int family = -1;                     // current family (a generic family never replaces a specific one)
    int lastNamed = -1, lastNamedPly = -1;   // latest named position (lichess name index)
    bool inBook = true;                  // the current position is a book position
    int leftBookPly = -1;                // first ply of the latest two-ply out-of-book run, -1 = none
    OpeningSideLabels side[2];           // [chess::White], [chess::Black]
    bool determined = false;
    int determinedPly = -1;
    DeterminedBy determinedBy = DeterminedBy::None;
    std::string rare;                    // lichess family of the latest named position no curated family covers
    std::vector<OpeningEvent> events;    // in ply order
};

// Replays the game from its start position. Standard start only (a custom FEN gives standardStart = false).
// maxPly: the opening counts as determined at this ply even while still in book (30 by default).
OpeningState classify(const chess::Game& game, const OpeningBook& book = OpeningBook::instance(), int maxPly = 30);

// ---- What the coach says -----------------------------------------------------------------------------------------
// A line of the coach's speech: a catalog key plus named, typed arguments. Maps 1:1 onto coach::Line / coach::Arg
// of the speech catalog (design §3.2): Kind::Opening -> Arg::Kind::Opening with the same text, Kind::Number ->
// Arg::Kind::Number. An Opening argument is a reference: "family:<id>", "variation:<id>" or "line:<lichess
// component>" (a lichess variation name composed per language, see OpeningTexts::arg).
struct OpeningArg {
    enum class Kind : uint8_t { Opening, Number };
    Kind kind = Kind::Opening;
    std::string text;
    int number = 0;
};
struct OpeningLine {
    std::string key;                                   // "opening.say.pw.both", "opening.family.italian.beginner"
    std::vector<std::pair<std::string, OpeningArg>> args;   // "{white}" -> args["white"]
};

// Decides what the coach says about the opening, from the game record alone (demonstration moves never reach the
// Game, so they never reach it either).
//
// Policy (level = coach level 0..6, design §1):
//   0      the rules lesson: silent.
//   all    once the opening is determined, both sides' openings in one sentence ("You opened with the Queen's
//          Gambit, and I declined it."), then one comment on what the opening leads to (once per opening per
//          session). Determined = a named leaf, two plies out of book, or a level-dependent ply limit (8 at levels
//          1-2, 12 at 3, 16 at 4, 20 at 5, 30 at 6).
//   1      family names; the coach's own tier-3 families are not named; beginner comments.
//   2      + notable variations that have a beginner comment (Fried Liver, Two Knights...).
//   3      + every notable variation, transpositions; beginner comments.
//   4      + advanced comments, "we have left known theory".
//   5      + the move where theory ended.
//   6      + deeper lichess components ("The exact line: English Attack.") in neutral wording, when both the
//          subtitle and the speech language can say them.
// At most one opening utterance per full move and 2 (levels 1-2), 3 (3-4) or 4 (5-6) per game; later news (a
// transposition, a new variation) is dropped once more than 4 plies old, the first summary never is.
class OpeningAnnouncer {
public:
    explicit OpeningAnnouncer(const OpeningBook& book = OpeningBook::instance());

    void setLevel(int level);                        // 0..6
    void setHumanColor(chess::Color c);              // the listener's side ("You opened with ...")
    // Languages of the subtitles and of the voice (design §1): composed lichess names are only used when both
    // can render them. Default: "en", "en".
    void setLanguages(const std::string& subtitle, const std::string& speech);
    int level() const { return level_; }

    void newGame();   // forgets the game, keeps the session's memory of comments already said
    void reset();     // forgets everything
    // Silent catch-up after moves were applied in bulk (--moves, a resumed game): everything the game has shown so
    // far counts as said.
    void catchUp(const chess::Game& game);

    // Lines to say now, in order (empty = nothing). Call after every completed move, and again when speech becomes
    // free if canSpeak was false (pending talk waits; the 4-ply staleness rule applies). Deterministic.
    std::vector<OpeningLine> update(const chess::Game& game, bool canSpeak = true);

    // The summary sentence for the end-of-game appraisal, from the game as it stands (empty when no opening can
    // be named). Does not change what the announcer remembers.
    std::vector<OpeningLine> summary(const chess::Game& game) const;

    int utterances() const { return utterances_; }   // opening utterances this game

private:
    const OpeningBook& book_;
    int level_ = 1;
    chess::Color human_ = chess::White;
    std::string subtitleLang_ = "en", speechLang_ = "en";
    std::set<std::string> said_;          // this game: "name:<ref>", "deep:<text>", "left_book", "rare"
    std::set<std::string> commentsSaid_;  // this session: comment keys
    bool summarySaid_ = false;
    bool takebackSinceTalk_ = false;
    int utterances_ = 0;
    int lastTalkPly_ = -100;
    int lastPlies_ = 0;

    struct Plan;
    Plan plan(const OpeningState& st) const;
    std::vector<OpeningLine> lines(const Plan& p, bool first) const;
    void markSaid(const Plan& p);
};

int openingPlyLimit(int level);   // the ply at which the opening counts as determined for this level

// ---- Texts ---------------------------------------------------------------------------------------------------------
// The opening texts of the 10 languages (assets/coach/openings/<code>.lang), to render OpeningLines without the
// speech catalog, and for the Opening arguments the catalog cannot resolve by key alone ("line:" references).
class OpeningTexts {
public:
    static const OpeningTexts& instance();                 // loads the embedded files on first use (thread-safe)
    bool load(std::string* error = nullptr);
    const std::string* find(const std::string& lang, const std::string& key) const;   // nullptr when absent

    // Text of an Opening argument. ref: "family:<id>" / "variation:<id>" (catalog key opening.<kind>.<id>, plus
    // "." + form unless the form is "" or "nom"), or "line:<component>" (a lichess variation name composed in
    // the language: English as is; French, German, Spanish from "<Proper> <Type>" when <Proper> is a proper name;
    // other languages only through the eponym table; Chinese subtitles keep the English words). spoken: the TTS
    // text (".spoken" keys, English respellings, " — " inside Russian/Ukrainian names made a hyphen).
    // Empty when the language cannot say it.
    std::string arg(const std::string& ref, const std::string& form, const std::string& lang, bool spoken) const;
    bool renderable(const OpeningLine& line, const std::string& lang) const;
    // Renders a line: variant key.N picked by variantSeed among the variants English defines; placeholders
    // {name} / {name:form}. Empty when a key or an argument is missing.
    std::string render(const OpeningLine& line, const std::string& lang, bool spoken, uint32_t variantSeed = 0) const;
    int variants(const std::string& key) const;            // variants defined in English (key, key.2, ...)

private:
    std::map<std::string, std::map<std::string, std::string>> langs_;   // language -> key -> value
    std::vector<std::pair<std::string, std::string>> respell_;          // English TTS respellings, longest first
    std::map<std::string, std::string> composeTypes_;                   // "Variation" -> "variation"
    std::map<std::string, std::string> components_;                     // "Exchange Variation" -> slug
    std::map<std::string, std::string> eponyms_;                        // "Najdorf" -> slug
    std::set<std::string> commonWords_;
    std::string compose(const std::string& component, const std::string& lang, bool spoken) const;
    bool properName(const std::string& words) const;
};

// Speech clean-up shared with the catalog: English respellings are in the .spoken keys; this turns " — " between
// two capitalised words (Russian and Ukrainian compound names: "Каро — Канн") into "-" so the voice does not pause.
std::string fixNameDashesForSpeech(const std::string& text);

}  // namespace coach
