#!/usr/bin/env python3
"""Generates src/gl/gl46.h and src/gl/gl46.cpp from third_party/khronos/GL/glcorearb.h.

Only core entry points from GL_VERSION_1_0 .. GL_VERSION_4_6 plus a few useful ARB/EXT
extensions are loaded. Run from the repository root:  python3 tools/gen_gl_loader.py
"""
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "third_party/khronos/GL/glcorearb.h")
EXTRA_EXT = {"GL_ARB_bindless_texture", "GL_EXT_texture_filter_anisotropic"}

text = open(SRC).read().splitlines()
block = None
funcs = []  # (name, block)
for line in text:
    m = re.match(r"#ifndef (GL_(VERSION_\d_\d|[A-Z]+_\w+))$", line)
    if m:
        block = m.group(1)
        continue
    m = re.match(r"GLAPI .*?APIENTRY (gl\w+) \(", line)
    if m and block and (block.startswith("GL_VERSION_") or block in EXTRA_EXT):
        funcs.append((m.group(1), block))

seen = set()
uniq = []
for f, b in funcs:
    if f not in seen:
        seen.add(f)
        uniq.append((f, b))

hdr = ["// Generated by tools/gen_gl_loader.py -- do not edit.",
       "#pragma once",
       "#include \"../../third_party/khronos/GL/glcorearb.h\"",
       "",
       "namespace gl46 {",
       "// Loads every entry point. Returns the number of core entry points that could not be",
       "// resolved (0 on a conforming 4.6 driver). 'getProc' is wglGetProcAddress/glXGetProcAddress.",
       "typedef void* (*GetProcFn)(const char* name);",
       "int load(GetProcFn getProc, const char** firstMissing);",
       "}",
       ""]
for f, b in uniq:
    hdr.append(f"extern PFN{f.upper()}PROC {f};")
open(os.path.join(ROOT, "src/gl/gl46.h"), "w").write("\n".join(hdr) + "\n")

cpp = ["// Generated by tools/gen_gl_loader.py -- do not edit.",
       "#include \"gl46.h\"",
       ""]
for f, b in uniq:
    cpp.append(f"PFN{f.upper()}PROC {f} = nullptr;")
cpp += ["", "namespace gl46 {", "int load(GetProcFn getProc, const char** firstMissing) {",
        "    int missing = 0;", "    if (firstMissing) *firstMissing = nullptr;"]
for f, b in uniq:
    core = b.startswith("GL_VERSION_")
    cpp.append(f"    {f} = (PFN{f.upper()}PROC)getProc(\"{f}\");")
    if core:
        cpp.append(f"    if (!{f}) {{ if (firstMissing && !*firstMissing) *firstMissing = \"{f}\"; ++missing; }}")
cpp += ["    return missing;", "}", "}"]
open(os.path.join(ROOT, "src/gl/gl46.cpp"), "w").write("\n".join(cpp) + "\n")
print(len(uniq), "entry points")
