#!/usr/bin/env python3
"""Generates src/tts/nfkd_table.cpp: the Unicode NFKD data used by the TTS text front end.

    python3 tools/tts_nfkd_table.py > src/tts/nfkd_table.cpp

The official Supertonic 3 front end calls unicodedata.normalize("NFKD", text) and its character
indexer only knows decomposed characters, so the runtime needs the same decomposition. The table
holds the full compatibility decomposition of every code point that has one (Hangul syllables
excepted, they are decomposed algorithmically) and the canonical combining class of every
combining mark, for the canonical reordering step. The committed file was generated with the
Unicode version printed in its header (Python's unicodedata).
"""
import sys
import unicodedata


def main():
    out = sys.stdout
    decomp = []
    for cp in range(0x110000):
        if 0xAC00 <= cp <= 0xD7A3:
            continue
        ch = chr(cp)
        d = unicodedata.normalize("NFKD", ch)
        if d != ch:
            decomp.append((cp, [ord(c) for c in d]))
    ccc = [(cp, unicodedata.combining(chr(cp))) for cp in range(0x110000) if unicodedata.combining(chr(cp))]
    pool = []
    offsets = []
    for _, d in decomp:
        offsets.append(len(pool))
        pool.extend(d)
    offsets.append(len(pool))
    assert len(pool) < 65536

    def emit(name, ctype, values, per_line, fmt):
        out.write("extern const %s %s[] = {\n" % (ctype, name))
        for i in range(0, len(values), per_line):
            out.write("    " + ",".join(fmt % v for v in values[i:i + per_line]) + ",\n")
        out.write("};\n")

    out.write("// Generated by tools/tts_nfkd_table.py from Python %s unicodedata (Unicode %s) -- do not edit.\n"
              % (sys.version.split()[0], unicodedata.unidata_version))
    out.write("// NFKD decompositions (Hangul syllables excepted) and canonical combining classes.\n")
    out.write("#include <cstddef>\n#include <cstdint>\n\nnamespace tts {\nnamespace text {\n\n")
    out.write("extern const size_t kNfkdCount = %d;\n" % len(decomp))
    emit("kNfkdCodepoints", "uint32_t", [c for c, _ in decomp], 12, "0x%x")
    emit("kNfkdOffsets", "uint16_t", offsets, 16, "%d")
    emit("kNfkdPool", "uint32_t", pool, 12, "0x%x")
    out.write("extern const size_t kCccCount = %d;\n" % len(ccc))
    emit("kCccCodepoints", "uint32_t", [c for c, _ in ccc], 12, "0x%x")
    emit("kCccClasses", "uint8_t", [k for _, k in ccc], 24, "%d")
    out.write("\n}  // namespace text\n}  // namespace tts\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
